CREATE TABLE article(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  resume VARCHAR(255),
  contenu TEXT,
  image VARCHAR(255),
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME ON UPDATE     CURRENT_TIMESTAMP
);